### ISSUE TITLE
Annotation file

### ISSUE THREAD

**Issue by iferres** [aghozlane/shaman#1]
Hi Amine! I was trying SHAMAN and I have a question. What's the expected format of the Annotation file? I'm working with a count table (tsv) but I do also have information about the taxonomy of each otu, I just don't know how to format it.

Hope you are fine, greetings from Uruguay!
Ignacio (Nacho)

**Comment by aghozlane** [comment]
Hi Nacho,

A tsv file is fine for the count/annotation/target file (to describe sample).
The first column should be key that is shared in the count and in the annotation
for the target file, it's just the sample name.
there is several example on the tutorial part, like this one:
http://shaman.c3bi.pasteur.fr/_w_153bca2e346ed1ff6542b144caec5d9da83167f70d5afec2/listeria.zip

Here is the description for the target file:
[Target_tuto.pdf](https://github.com/aghozlane/shaman/files/1559566/Target_tuto.pdf)

Greetings from Paris,
Amine
