### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by courtney0thomas** [aghozlane/shaman#4]
Hi, I'm trying to install shaman on R 3.6.1 using the code provided:
# Load shiny packages
if(!require('shiny')){
 install.packages('shiny')
 library(shiny)
}

# Install dependencies, download last version of SHAMAN from github and run shaman in one command :
runGitHub('aghozlane/shaman')

and I get a lot of warning messages but ultimately R studio says this:

> runGitHub('aghozlane/shaman')
Downloading https://github.com/aghozlane/shaman/archive/master.tar.gz
Loading required package: DESeq2shaman
Warning in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘DESeq2shaman’
Downloading GitHub repo aghozlane/DESeq2shaman@master
✔  checking for file ‘/private/var/folders/_s/s02mpvvn6_7494rb08sycqgr0000gp/T/RtmpmMteBC/remotesf622370c5c16/aghozlane-DESeq2shaman-282594b/DESCRIPTION’
─  preparing ‘DESeq2shaman’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
✔  checking vignette meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘DESeq2shaman_1.6.3.tar.gz’
   
* installing *source* package ‘DESeq2shaman’ ...
** using staged installation
** libs
#lists libraries#
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o DESeq2shaman.so DESeq2.o RcppExports.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [DESeq2shaman.so] Error 1
ERROR: compilation failed for package ‘DESeq2shaman’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/DESeq2shaman’
Error: Failed to install 'DESeq2shaman' from GitHub:
  (converted from warning) installation of package ‘/var/folders/_s/s02mpvvn6_7494rb08sycqgr0000gp/T//RtmpmMteBC/filef622c71c496/DESeq2shaman_1.6.3.tar.gz’ had non-zero exit status

**Comment by aghozlane** [comment]
Hi you need to install gfortran to build tools on mac https://cran.r-project.org/bin/macosx/tools/

this one should be the most appropriate for your version of mac: https://cran.r-project.org/bin/macosx/tools/gfortran-6.1.pkg
