### ISSUE TITLE
object 'exp_track_nm' not found in `shaman_score_hic_track()`

### ISSUE THREAD

**Issue by jiangpuxuan** [aghozlane/shaman#5]
I finished `gtrack.2d.import()`, `gdb.reload()` and `shaman_shuffle_hic_track()` and everything is OK.
However, there is something wrong in  `shaman_score_hic_track()` :
```
shaman_score_hic_track(
  track_db=groot, 
  work_dir=tempdir(),
  score_track_nm=score_track_name, 
  obs_track_nms=track_name,
  max_jobs= 3)

```
The error is:
```
Error in paste("Missing exp_track_nm (", exp_track_nm[!gtrack.exists(exp_track_nms)],  : 
  object 'exp_track_nm' not found
```
This error may indicate that something in the output of `shaman_shuffle_hic_track()`  is missed.
I then checked `/db/genome3d/hg38/tracks/`, and that directory did not have something like `exp_track_nm` in fact. How could I fix this?

BTW, could I run this function like this ?
```
options(shaman.mc_support=1)
shaman_score_hic_track(
  track_db=groot, 
  work_dir=tempdir(),
  score_track_nm=score_track_name, 
  obs_track_nms=track_name,
  exp_track_nm=track_name,# same as obs_track_nms
  max_jobs= 3)

```

Thank you for your help!

**Comment by aghozlane** [comment]
Dear user, can you explain how you obtained this ? is it the same shaman ?

**Comment by jiangpuxuan** [comment]
> Dear user, can you explain how you obtained this ? is it the same shaman ?

I felt sorry for mistaking it. 
It is not the same `shaman`.
